### ISSUE TITLE
Support for non-x86 platforms?

### ISSUE THREAD

**Issue by mickeyl** [sisoftrg/ayplayer#1]
Thanks for this great project. I have seen some embedded x86 asm in there – is that crucial for the project or just an optimization? I ask because I'd like to compile this for other CPU architectures, e.g. ARM (iOS).

**Comment by sisoftrg** [comment]
Back in time then this project was started some asm optimizations was useful. but this code is optional and not compiled under non-x86 architectures. For example, player works well on amd64.
I'm not tried to compile\run it under other platforms, but I think that it can be possible, may be with some small modifications.

**Comment by sisoftrg** [comment]
Tested on Raspberry PI 3 (ARMv7, Raspbian distro) without any modifications. All works well.
